---
- hosts: all
  gather_facts: yes
  become: True

- hosts: web_node
  roles:
    - cmndrsp0ck.nginx443-backend
  become: True

- hosts: load_balancer
  roles:
    - cmndrsp0ck.haproxy-tls-pass
  become: True
